# Generated by Django 4.1.7 on 2023-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='filesDocumentation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
