# Generated by Django 4.1.7 on 2023-04-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_log_filesdocumentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='filesDocumentation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
