# Generated by Django 4.1.7 on 2023-04-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_log_filesdocumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='filesDocumentation',
        ),
        migrations.AddField(
            model_name='log',
            name='filesDocumentation',
            field=models.ManyToManyField(null=True, to='User.imgdoc'),
        ),
    ]
