# Generated by Django 4.1.7 on 2023-04-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_imgdoc_remove_log_filesdocumentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdoc',
            name='dirname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
